const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("burnBrief", {
  status: () => ipcRenderer.invoke("burnbrief:status"),
  items: (opts) => ipcRenderer.invoke("burnbrief:items", opts),
  itemStatus: (id, status) => ipcRenderer.invoke("burnbrief:itemStatus", id, status),
  runNow: () => ipcRenderer.invoke("burnbrief:runNow"),
  lastRun: () => ipcRenderer.invoke("burnbrief:lastRun"),
  profile: () => ipcRenderer.invoke("burnbrief:profile"),
  setProfile: (text, aliases) => ipcRenderer.invoke("burnbrief:setProfile", text, aliases),
  profileInfer: () => ipcRenderer.invoke("burnbrief:profileInfer"),
  goalAdd: (desc) => ipcRenderer.invoke("burnbrief:goalAdd", desc),
  goalStatus: (id, action) => ipcRenderer.invoke("burnbrief:goalStatus", id, action),
  reprioritize: () => ipcRenderer.invoke("burnbrief:reprioritize"),
  digest: (day) => ipcRenderer.invoke("burnbrief:digest", day),
  loopDone: (id) => ipcRenderer.invoke("burnbrief:loopDone", id),
  loopReopen: (id) => ipcRenderer.invoke("burnbrief:loopReopen", id),
  loops: () => ipcRenderer.invoke("burnbrief:loops"),
  brcWeather: () => ipcRenderer.invoke("burnbrief:brcWeather"),
  backdrop: () => ipcRenderer.invoke("burnbrief:backdrop"),
  digestRun: () => ipcRenderer.invoke("burnbrief:digestRun"),
  backendSet: (backend) => ipcRenderer.invoke("burnbrief:backendSet", backend),
  digestAutosend: (enabled) => ipcRenderer.invoke("burnbrief:digestAutosend", enabled),
  exportIcs: (item) => ipcRenderer.invoke("burnbrief:exportIcs", item),
  openUrl: (url) => ipcRenderer.invoke("burnbrief:openUrl", url),
  joinGroup: (url) => ipcRenderer.invoke("burnbrief:joinGroup", url),
  openWhatsApp: () => ipcRenderer.invoke("burnbrief:openWhatsApp"),
  consent: () => ipcRenderer.invoke("burnbrief:consent"),
  consentGrant: () => ipcRenderer.invoke("burnbrief:consentGrant"),
  onRefreshed: (cb) => ipcRenderer.on("burnbrief:refreshed", (_e, data) => cb(data)),
});
